id: P008165
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG17431
  title: ཚད་མ་རིགས་གཞུང་རྒྱ་མཚོ།
  author: ''
  volumes:
    2fdd8b434f144e10a2c9dea6812efe1e:
      image_group_id: I1KG110447
      title: ''
      volume_number: 1
      total_pages: 958
      base_file: v001.txt
    93f446d14676444b9a61f0fcf40a6c74:
      image_group_id: I1KG110448
      title: ''
      volume_number: 2
      total_pages: 818
      base_file: v002.txt
