id: I49557261
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-28T08:56:42+00:00'
last_modified: '2022-06-09T04:57:06.591018+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG17431
  title: ཚད་མ་རིགས་གཞུང་རྒྱ་མཚོ།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    4FF7:
      image_group_id: I1KG110447
      title: ''
      total_pages: 958
      order: 1
      base_file: 4FF7.txt
    '7691':
      image_group_id: I1KG110448
      title: ''
      total_pages: 818
      order: 2
      base_file: 7691.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
